.\" Manpage for instantrom.
.\" Contact me here https://github.com/JackofSpades707 to correct errors or typos.
.TH man 1 "27 Sep 2016" "1.0" "instant torrent man page"
.SH NAME
instanttorrent \- Downloads a torrent
.SH SYNOPSIS
instanttorrent
.SH DESCRIPTION
instanttorrent is python script for downloading various torrents.
.SH OPTIONS
The instanttorrent does not take any options currently.
.SH SEE ALSO
To Be Added
.SH BUGS
No known bugs.
.SH AUTHOR
https://github.com/JackofSpades707
